title: "the %rax exchange"
description: >-
  Vulnerability research, malware reverse engineering, and low-level systems
  notes by Lewis Patten.
url: "https://xchg-rax-rax.github.io"
locale: "en-GB"
lang: "en"
timezone: "Etc/UTC"

remote_theme: kitian616/jekyll-TeXt-theme

text_skin: "dark"
highlight_theme: "tomorrow-night-eighties"

repository: xchg-rax-rax/xchg-rax-rax.github.io

author:
  name: "Lewis Patten"
  url: "https://github.com/xchg-rax-rax"

paginate: 8
paginate_path: /page:num
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

include:
  - _pages

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      aside:
        toc: true
      show_edit_on_github: false
      show_subscribe: false
      pageview: false
      modify_date: ""
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: article
      aside:
        toc: true
