title: "the %rax exchange"
description: >-
  Vulnerability research, malware reverse engineering, and low-level systems
  notes by Lewis Patten.
url: "https://xchg-rax-rax.github.io"
locale: "en-GB"
lang: "en"

remote_theme: riggraz/no-style-please

appearance: "dark"
appearance_toggle: true

back_to_top: true
back_to_top_text: "↑ back to top"

copyright: "© Lewis Patten"

menu:
  - title: "~"
    url: "/"
  - title: "about"
    url: "/about/"
  - title: "tags"
    url: "/tags/"
  - title: "rss"
    url: "/feed.xml"

author:
  name: "Lewis Patten"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

include:
  - _pages

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
